from enum import StrEnum

class InventoryReferenceType(StrEnum):
    SALE = "SALE"
    STOCK_TRANSFER = "STOCK_TRANSFER"
    PRODUCTION_ORDER = "PRODUCTION_ORDER"
    PURCHASE = "PURCHASE"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
    CUSTOMER_RETURN = "CUSTOMER_RETURN"
    SUPPLIER_RETURN = "SUPPLIER_RETURN"