# -------------------------
# Dev Dockerfile
# -------------------------
FROM python:3.12-slim

WORKDIR /app

RUN echo "deb http://ftp.us.debian.org/debian trixie main" > /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends curl

# Instala uv
RUN set -eux \
    && curl -LsSf https://astral.sh/uv/install.sh | sh

# Agrega uv a PATH
ENV PATH="/root/.local/bin:/root/.cargo/bin:${PATH}"
ENV UV_PROJECT_ENVIRONMENT=system

# Copia solo deps primero (cacheable)
COPY pyproject.toml uv.lock ./

# Instala deps (incluye dev si quieres)
RUN uv sync --frozen

# Copia el código
COPY app ./app

# Exponer puerto
EXPOSE 8000

ENTRYPOINT ["uv", "run", "uvicorn"]
CMD ["app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]