services:
  db:
    image: postgres:15
    restart: always 
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lfu

  amd-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    restart: always
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    image: backend_jean

volumes:
  postgres_data: