
services:
  test-db:
    image: postgres:15-alpine
    container_name: galeria-db-test
    ports:
      - "5434:5432"
    env_file:
      - .env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U angeloviu -d test_jeans_galery"]
      interval: 5s
      retries: 5
  test-redis-app:
    image: redis:latest
    ports:
      - "6380:6379"
  galeria-test-app:
    command: ['pytest', '-v']
    depends_on:
      - test-db
      - test-redis
    env_file:
      - .env.test
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ./tests:/tests
    