services:
  test-db:
    image: postgres:15
    container_name: backend-test-db
    env_file:
      - .env.test
    ports:
      - "5436:5432"

  test-redis:
    image: redis:latest
    container_name: backend-test-redis
    ports:
      - "6382:6379"
