"""adding new index on public_id column in MediaImageTable

Revision ID: 08dbc8d6c638
Revises: 97ff7f19cfd7
Create Date: 2026-02-23 01:06:11.219665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08dbc8d6c638'
down_revision: Union[str, Sequence[str], None] = '97ff7f19cfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_image_public_id'), 'image', ['public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_public_id'), table_name='image')
    # ### end Alembic commands ###
