"""Se agregao columna 'slug' a la Tabla Product

Revision ID: 0e6eadc205ca
Revises: 
Create Date: 2025-12-09 18:15:19.832131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e6eadc205ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'product', ['nombre'])
    op.create_unique_constraint(None, 'usertable', ['nombre'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usertable', type_='unique')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'slug')
    # ### end Alembic commands ###
