"""delete null type hint of sku column in VariantSize table

Revision ID: 18a5d418d133
Revises: f1ff09ee9186
Create Date: 2026-04-16 23:10:43.632523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a5d418d133'
down_revision: Union[str, Sequence[str], None] = 'f1ff09ee9186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variant_size', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variant_size', 'sku',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
