"""add price column in product table

Revision ID: 367c336618d2
Revises: 8a4df7eeb04c
Create Date: 2026-05-20 23:45:18.798085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '367c336618d2'
down_revision: Union[str, Sequence[str], None] = '8a4df7eeb04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_movement')
    op.create_index('uq_only_one_primary_per_owner', 'image', ['owner_type', 'owner_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.add_column('product', sa.Column('price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    op.drop_index('uq_only_one_primary_per_owner', table_name='image', postgresql_where=sa.text('is_primary = true'))
    op.create_table('inventory_movement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_size_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('RESTOCK', 'MANUAL_ADJUSTMENT', 'SALE', 'RETURN', name='inventory_movement_type'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_movement_pkey'))
    )
    # ### end Alembic commands ###
