"""add price column in product table

Revision ID: 367c336618d2
Revises: 8a4df7eeb04c
Create Date: 2026-05-20 23:45:18.798085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '367c336618d2'
down_revision: Union[str, Sequence[str], None] = '8a4df7eeb04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_only_one_primary_per_owner', 'image', ['owner_type', 'owner_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.add_column('product', sa.Column('price', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    op.drop_index('uq_only_one_primary_per_owner', table_name='image', postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###
