"""added new unique constraint at (product_id, color) and deleted the compose index at (colot, product_id)

Revision ID: 4d986d598b1e
Revises: 7e99854ec37a
Create Date: 2026-02-08 00:32:00.685449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d986d598b1e'
down_revision: Union[str, Sequence[str], None] = '7e99854ec37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_nombre_trgm'), table_name='product', postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('usertable', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_nombre_trgm'), table_name='usertable', postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_variant_color_product_id'), table_name='variant')
    op.create_unique_constraint('uq_variant_product_color', 'variant', ['product_id', 'color'])
    op.drop_index(op.f('ix_variant_size_size_variant_id'), table_name='variant_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_variant_size_size_variant_id'), 'variant_size', ['size', 'variant_id'], unique=False)
    op.drop_constraint('uq_variant_product_color', 'variant', type_='unique')
    op.create_index(op.f('ix_variant_color_product_id'), 'variant', ['color', 'product_id'], unique=False)
    op.create_index(op.f('ix_user_nombre_trgm'), 'usertable', ['nombre'], unique=False, postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    op.alter_column('usertable', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_product_nombre_trgm'), 'product', ['nombre'], unique=False, postgresql_ops={'nombre': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
