"""optimizating index on product and image table

Revision ID: 505ae40d3c7c
Revises: 08dbc8d6c638
Create Date: 2026-03-20 03:48:55.345982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505ae40d3c7c'
down_revision: Union[str, Sequence[str], None] = '08dbc8d6c638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_owner'), table_name='image')
    op.drop_index(op.f('ix_image_owner_type'), table_name='image')
    op.drop_index(op.f('ix_image_public_id'), table_name='image')
    op.drop_index(op.f('ix_product_marca'), table_name='product')
    op.drop_index(op.f('ix_variant_size_size_variant_id'), table_name='variant_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_variant_size_size_variant_id'), 'variant_size', ['size', 'variant_id'], unique=False)
    op.create_index(op.f('ix_product_marca'), 'product', ['marca'], unique=False)
    op.create_index(op.f('ix_image_public_id'), 'image', ['public_id'], unique=False)
    op.create_index(op.f('ix_image_owner_type'), 'image', ['owner_type'], unique=False)
    op.create_index(op.f('ix_image_owner'), 'image', ['owner_type', 'owner_id'], unique=False)
    # ### end Alembic commands ###
