"""added new columns on user table and composed index

Revision ID: 7e99854ec37a
Revises: de84557f6058
Create Date: 2026-02-02 23:06:36.088743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e99854ec37a'
down_revision: Union[str, Sequence[str], None] = 'de84557f6058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_variant_color_product_id", table_name="variant")

    # 2) crear unique (product_id, color) -> crea índice único implícito
    op.create_unique_constraint(
        "uq_variant_product_color",
        "variant",
        ["product_id", "color"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
     # Re-create old indexes you dropped
    op.drop_constraint("uq_variant_product_color", "variant", type_="unique")

    op.create_index(
        "ix_variant_color_product_id",
        "variant",
        ["color", "product_id"],
        unique=False,
    )
    # (Opcional) no dropeo pg_trgm aquí
    # op.execute("DROP EXTENSION IF EXISTS pg_trgm")
