"""add is_primary column on Image table and unique constraint to handle unique primary image per owner group

Revision ID: 8a4df7eeb04c
Revises: 44e49538e231
Create Date: 2026-04-28 23:57:37.816228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a4df7eeb04c'
down_revision: Union[str, Sequence[str], None] = '44e49538e231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # op.create_index('uq_only_one_primary_per_owner', 'image', ['owner_type', 'owner_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('uq_only_one_primary_per_owner', table_name='image', postgresql_where=sa.text('is_primary = true'))
    op.drop_column('image', 'is_primary')
    # ### end Alembic commands ###
