"""Adding unique constraint at column 'orden' on Slide Table

Revision ID: 97ff7f19cfd7
Revises: f674535a3280
Create Date: 2026-02-20 22:28:25.822584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ff7f19cfd7'
down_revision: Union[str, Sequence[str], None] = 'f674535a3280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'model_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'slide', ['orden'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slide', type_='unique')
    op.alter_column('product', 'model_family',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
