"""migration current database model to database-model-v1 structure

Revision ID: da0bc75361de
Revises: f93b57b8e121
Create Date: 2026-06-11 02:23:29.587077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da0bc75361de'
down_revision: Union[str, Sequence[str], None] = 'f93b57b8e121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('supply_movement')
    # op.drop_table('pricing_rules')
    # op.drop_table('product_pricing_rules')
    
    op.drop_table('supply')
    op.drop_column('product', 'model_family')

    # Arreglar lo de aca
    op.alter_column(
        "product",
        "marca",
        new_column_name="brand"
    )

    op.alter_column(
        "product",
        "categoria",
        new_column_name="category"
    )

    brand_enum = postgresql.ENUM(
        "BGOO",
        "AMD",
        name="brand_type"
    )

    category_enum = postgresql.ENUM(
        "PANT",
        "SHIRT",
        "SHORT",
        "JACKET",
        name="category_type"
    )

    fit_enum = postgresql.ENUM(
        "SKINNY",
        "SLIM",
        "REGULAR",
        "STRAIGHT",
        "RELAXED",
        "LOOSE",
        "MOM_FIT",
        "BOOTCUT",
        "TAPERED",
        "BOXY",
        name="fit_type"
    )

    brand_enum.create(op.get_bind(), checkfirst=True)
    category_enum.create(op.get_bind(), checkfirst=True)
    fit_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        """
        ALTER TABLE product
        ALTER COLUMN brand
        TYPE brand_type
        USING brand::brand_type
        """
    )

    op.execute(
        """
        ALTER TABLE product
        ALTER COLUMN category
        TYPE category_type
        USING category::category_type
        """
    )

    op.execute(
        """
        ALTER TABLE product
        ALTER COLUMN fit
        TYPE fit_type
        USING fit::fit_type
        """
    )

    op.alter_column('product', 'fit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SKINNY', 'SLIM', 'REGULAR', 'STRAIGHT', 'RELAXED', 'LOOSE', 'MOM_FIT', 'BOOTCUT', 'TAPERED', 'BOXY', name='fit_type'),
               existing_nullable=True)
    
    op.execute("""
    DROP INDEX IF EXISTS ix_product_category_model_family
    """)
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TABLE product
    ALTER COLUMN fit
    TYPE VARCHAR(20)
    USING fit::text
    """)

    op.execute("""
    ALTER TABLE product
    ALTER COLUMN category
    TYPE VARCHAR(20)
    USING category::text
    """)

    op.execute("""
    ALTER TABLE product
    ALTER COLUMN brand
    TYPE VARCHAR(20)
    USING brand::text
    """)

    op.alter_column(
        "product",
        "brand",
        new_column_name="marca"
    )

    op.alter_column(
        "product",
        "category",
        new_column_name="categoria"
    )

    op.add_column(
        "product",
        sa.Column(
            "model_family",
            sa.String(length=100),
            nullable=True
        )
    )

    op.drop_index(
        op.f("ix_product_category"),
        table_name="product"
    )

    op.create_index(
        op.f("ix_product_category_model_family"),
        "product",
        ["category", "model_family"],
        unique=False
    )

    op.create_table('supply',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company', postgresql.ENUM('OLD_DENIM', 'CHOCCA', name='company_type'), autoincrement=False, nullable=False),
    sa.Column('current_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('minimum_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_pkey')),
    sa.UniqueConstraint('code', name=op.f('supply_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )

    op.create_table('supply_movement',
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('previous_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('RESTOCK', 'MANUAL_ADJUSTMENT', 'SALE', 'RETURN', name='inventory_movement_type'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('supply_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('supply_movement_pkey'))
    )


    fit_enum = postgresql.ENUM(
        "SKINNY",
        "SLIM",
        "REGULAR",
        "STRAIGHT",
        "RELAXED",
        "LOOSE",
        "MOM_FIT",
        "BOOTCUT",
        "TAPERED",
        "BOXY",
        name="fit_type"
    )

    category_enum = postgresql.ENUM(
        "PANT",
        "SHIRT",
        "SHORT",
        "JACKET",
        name="category_type"
    )

    brand_enum = postgresql.ENUM(
        "BGOO",
        "AMD",
        name="brand_type"
    )

    fit_enum.drop(op.get_bind(), checkfirst=True)
    category_enum.drop(op.get_bind(), checkfirst=True)
    brand_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
