"""add is_active and discount column in product table

Revision ID: f1bb5fe45efb
Revises: 367c336618d2
Create Date: 2026-05-25 00:28:13.651448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1bb5fe45efb'
down_revision: Union[str, Sequence[str], None] = '367c336618d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('product', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount_percentage')
    op.drop_column('product', 'is_active')
    # ### end Alembic commands ###
