"""add stock in VariantSize table to handle stock by variant sizes and add Inventory Movement to monitor movements and actions of inventory

Revision ID: f1ff09ee9186
Revises: 505ae40d3c7c
Create Date: 2026-04-14 02:31:14.783562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1ff09ee9186'
down_revision: Union[str, Sequence[str], None] = '505ae40d3c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant_size', sa.Column('stock', sa.Integer(), nullable=True))
    op.execute("""
    UPDATE variant_size SET stock = 0 WHERE stock IS NULL
    """)

    op.alter_column("variant_size", "stock", nullable=False)
    op.add_column('variant_size', sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant_size', 'sku')
    op.drop_column('variant_size', 'stock')
    # ### end Alembic commands ###
