"""deleted the server default of column model_family at Product Table

Revision ID: f674535a3280
Revises: 839a9ff11bea
Create Date: 2026-02-14 04:14:50.160318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f674535a3280'
down_revision: Union[str, Sequence[str], None] = '839a9ff11bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'model_family',
               existing_type=sa.VARCHAR(length=50),
               server_default=None
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'product',
        'model_family',
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'unknown'")
    )
    # ### end Alembic commands ###
